/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Telas;

import javax.swing.JOptionPane;

/**
 *
 * @author Marcos
 */
public class Operações extends javax.swing.JFrame {

    private static int indice;
    private static boolean achou = false;
    private static int indiceConta;

    /**
     * Creates new form Operações
     */
    public Operações() {
        initComponents();
    }

    private void resetCampos() {
        valorSaque.setText("");
        valorDeposito.setText("");
    }

    private void messageContaInvalida() {
        JOptionPane.showMessageDialog(null, "Informe uma conta válida!");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        cpfOpera = new javax.swing.JTextField();
        resultadoBusca = new javax.swing.JLabel();
        selecBotao = new javax.swing.JButton();
        valorSaque = new javax.swing.JTextField();
        verSaldo = new javax.swing.JButton();
        sacarValor = new javax.swing.JButton();
        depositarValor = new javax.swing.JButton();
        remuneraConta = new javax.swing.JButton();
        valorDeposito = new javax.swing.JTextField();
        voltar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Realizar operação em conta existente");

        jLabel2.setText("Informe o CPF do titular da conta:");

        selecBotao.setText("Selecionar");
        selecBotao.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                selecBotaoMouseClicked(evt);
            }
        });

        verSaldo.setText("Ver Saldo");
        verSaldo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                verSaldoMouseClicked(evt);
            }
        });

        sacarValor.setText("Sacar Valor");
        sacarValor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                sacarValorMouseClicked(evt);
            }
        });

        depositarValor.setText("Depositar Valor");
        depositarValor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                depositarValorMouseClicked(evt);
            }
        });

        remuneraConta.setText("Remunera Conta");
        remuneraConta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                remuneraContaMouseClicked(evt);
            }
        });

        voltar.setText("Voltar");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(96, 96, 96)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(verSaldo, javax.swing.GroupLayout.PREFERRED_SIZE, 311, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(valorDeposito)
                                            .addComponent(valorSaque))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(depositarValor, javax.swing.GroupLayout.DEFAULT_SIZE, 231, Short.MAX_VALUE)
                                            .addComponent(sacarValor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                    .addComponent(remuneraConta, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(0, 88, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(resultadoBusca, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addComponent(jLabel2)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(cpfOpera)))
                                .addGap(7, 7, 7)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(voltar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(selecBotao, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel1)
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(cpfOpera, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(selecBotao))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(resultadoBusca, javax.swing.GroupLayout.DEFAULT_SIZE, 22, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(verSaldo)
                        .addGap(34, 34, 34))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(valorSaque, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(sacarValor)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(depositarValor)
                    .addComponent(valorDeposito, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(remuneraConta)
                .addGap(24, 24, 24)
                .addComponent(voltar)
                .addGap(18, 18, 18))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void selecBotaoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_selecBotaoMouseClicked
        achou = false;
        resetCampos();
        for (int i = 0; i < ManterClii.listaDeClientes.size(); i++) {
            if (cpfOpera.getText().equals(ManterClii.listaDeClientes.get(i).getCpf())) {
                achou = true;
                indice = i;
                indiceConta = ManterClii.listaDeClientes.get(indice).getIdConta();

            }
        }
        if (achou) {
            if (!ManterClii.listaDeClientes.get(indice).getHaveConta()) {
                resultadoBusca.setText("Esse CPF não possui conta vinculada!");
                achou = false;
            } else {
                resultadoBusca.setText("Nome do titular da conta: " + ManterClii.listaDeClientes.get(indice).getNome() + " " + ManterClii.listaDeClientes.get(indice).getSobrenome());
            }
        } else {
            resultadoBusca.setText("O CPF informado não foi encontrado na base de dados!");
        }
    }//GEN-LAST:event_selecBotaoMouseClicked

    private void sacarValorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sacarValorMouseClicked
        if (!achou) {
            messageContaInvalida();
            resetCampos();
        }
    }//GEN-LAST:event_sacarValorMouseClicked

    private void verSaldoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_verSaldoMouseClicked
        if (!achou) {
            messageContaInvalida();
            resetCampos();
        } else {
            JOptionPane.showMessageDialog(null, "Saldo em conta: R$" + ManterClii.listaDeContas.get(indiceConta).getSaldo());
        }
    }//GEN-LAST:event_verSaldoMouseClicked

    private void depositarValorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_depositarValorMouseClicked
        if (!achou) {
            messageContaInvalida();
            resetCampos();
        } else if("".equals(valorDeposito.getText())) {
            JOptionPane.showMessageDialog(null, "Informe um valor para depositar");
        }
        else {
            JOptionPane.showMessageDialog(null, "Valor depositado na conta: R$"+ valorDeposito.getText()) ;
        }
        
    }//GEN-LAST:event_depositarValorMouseClicked

    private void remuneraContaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_remuneraContaMouseClicked
        if (!achou) {
            messageContaInvalida();
            resetCampos();
        }
    }//GEN-LAST:event_remuneraContaMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Operações.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Operações.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Operações.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Operações.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Operações().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField cpfOpera;
    private javax.swing.JButton depositarValor;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JButton remuneraConta;
    private javax.swing.JLabel resultadoBusca;
    private javax.swing.JButton sacarValor;
    private javax.swing.JButton selecBotao;
    private javax.swing.JTextField valorDeposito;
    private javax.swing.JTextField valorSaque;
    private javax.swing.JButton verSaldo;
    private javax.swing.JButton voltar;
    // End of variables declaration//GEN-END:variables
}
