/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Telas;

import Algs.*;

/**
 *
 * @author Marcos
 */
public class VincularClienteConta extends javax.swing.JFrame {

    private int opt = 0;
    private static int indice;

    /**
     * Creates new form VincularClienteConta
     */
    public VincularClienteConta() {
        initComponents();
        setCamposInvisible();
    }

    private void setCamposInvisible() {
        label1.setVisible(false);
        label2.setVisible(false);
        label3.setVisible(false);
        campo1.setVisible(false);
        campo2.setVisible(false);
        campo3.setVisible(false);
        vincularConta.setVisible(false);
    }

    private void setCamposVisible(int opt) {
        if (opt == 0) {
            label1.setVisible(true);
            label2.setVisible(true);
            label3.setVisible(false);
            campo1.setVisible(true);
            campo2.setVisible(true);
            campo3.setVisible(false);
            vincularConta.setVisible(true);
            label2.setText("Limite de crédito: ");
            campo1.setText("");
            campo2.setText("");
        } else if (opt == 1) {
            label1.setVisible(true);
            label2.setVisible(true);
            label3.setVisible(true);
            campo1.setVisible(true);
            campo2.setVisible(true);
            campo3.setVisible(true);
            vincularConta.setVisible(true);
            label2.setText("Montante mínimo: ");
            campo1.setText("");
            campo2.setText("");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        contaCPF = new javax.swing.JTextField();
        selecionar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        comboBoxConta = new javax.swing.JComboBox<>();
        resultadoBusca = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        voltarButton = new javax.swing.JButton();
        campo3 = new javax.swing.JTextField();
        vincularConta = new javax.swing.JButton();
        campo2 = new javax.swing.JTextField();
        campo1 = new javax.swing.JTextField();
        label1 = new javax.swing.JLabel();
        label2 = new javax.swing.JLabel();
        label3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Vincular Cliente a uma conta");

        selecionar.setText("Selecionar");
        selecionar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                selecionarMouseClicked(evt);
            }
        });

        jLabel2.setText("CPF:");

        jLabel3.setText("Tipo de conta:");

        comboBoxConta.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Conta Corrente", "Conta Investimento" }));

        jLabel4.setText("Informe um CPF válido e o tipo de conta a ser vinculado");

        voltarButton.setText("Voltar");
        voltarButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                voltarButtonMouseClicked(evt);
            }
        });

        vincularConta.setText("Vincular");
        vincularConta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                vincularContaMouseClicked(evt);
            }
        });

        label1.setText("Depósito inicial:");

        label2.setText("Campo 2:");

        label3.setText("Depósito mínimo:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(136, 136, 136)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addComponent(jLabel4))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(18, 18, 18)
                                .addComponent(contaCPF)
                                .addGap(34, 34, 34)
                                .addComponent(selecionar)
                                .addGap(39, 39, 39)
                                .addComponent(voltarButton))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(label2)
                                    .addComponent(label3))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(campo3, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(campo1, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(campo2, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 65, Short.MAX_VALUE)
                                        .addComponent(vincularConta))))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel3)
                                        .addGap(18, 18, 18)
                                        .addComponent(comboBoxConta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(resultadoBusca))
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addGap(51, 51, 51))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1)
                        .addGap(7, 7, 7)
                        .addComponent(jLabel4)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(contaCPF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(61, 61, 61)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(selecionar)
                            .addComponent(voltarButton))))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(comboBoxConta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addComponent(resultadoBusca)
                .addGap(65, 65, 65)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label1)
                    .addComponent(campo1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(campo2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(vincularConta)
                    .addComponent(label2, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(campo3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label3))
                .addContainerGap(70, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void selecionarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_selecionarMouseClicked
        boolean achou = false;
        setCamposInvisible();
        for (int i = 0; i < ManterClii.listaDeClientes.size(); i++) {
            if (contaCPF.getText() == ManterClii.listaDeClientes.get(i).getCpf());
            {
                //cli = ManterClii.listaDeClientes.get(i);
                achou = true;
                indice = i;
                break;
            }
        }
        if (achou) {
            if (ManterClii.listaDeClientes.get(indice).getHaveConta()) {
                resultadoBusca.setText("Já existe uma conta vinculada a esse CPF!");
               
            } else {
                opt = comboBoxConta.getSelectedIndex();
                resultadoBusca.setText(ManterClii.listaDeClientes.get(indice).getCpf());/*"Cliente: " + ManterClii.listaDeClientes.get(i).getNome() + " " + ManterClii.listaDeClientes.get(i).getSobrenome()
                        + "           -          Selecionado: " + comboBoxConta.getSelectedItem());
                */setCamposVisible(opt);
            }
        } else {
            resultadoBusca.setText("O CPF informado não foi encontrado na base de dados!");
        }
        achou = false;
    }//GEN-LAST:event_selecionarMouseClicked

    private void voltarButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_voltarButtonMouseClicked
        setVisible(false);
    }//GEN-LAST:event_voltarButtonMouseClicked

    private void vincularContaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_vincularContaMouseClicked

        if (opt == 0) {

            double limite = Double.parseDouble(campo2.getText());
            double depIni = Double.parseDouble(campo1.getText());

            ContaCorrente contac = new ContaCorrente(limite, depIni, ManterClii.listaDeClientes.get(indice).getCpf());
            ManterClii.listaDeContas.add(contac);

        } else if (opt == 1) {

            double depIni = Double.parseDouble(campo1.getText());
            double depMin = Double.parseDouble(campo3.getText());
            double montanteMin = Double.parseDouble(campo2.getText());
            ContaInvestimento contai = new ContaInvestimento(depMin, montanteMin, depIni, ManterClii.listaDeClientes.get(indice).getCpf());
            ManterClii.listaDeContas.add(contai);
        }
        ManterClii.listaDeClientes.get(indice).setIdConta((ManterClii.listaDeContas.size() - 1));
    }//GEN-LAST:event_vincularContaMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VincularClienteConta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VincularClienteConta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VincularClienteConta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VincularClienteConta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VincularClienteConta().setVisible(true);
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField campo1;
    private javax.swing.JTextField campo2;
    private javax.swing.JTextField campo3;
    private javax.swing.JComboBox<String> comboBoxConta;
    private javax.swing.JTextField contaCPF;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel label1;
    private javax.swing.JLabel label2;
    private javax.swing.JLabel label3;
    private javax.swing.JLabel resultadoBusca;
    private javax.swing.JButton selecionar;
    private javax.swing.JButton vincularConta;
    private javax.swing.JButton voltarButton;
    // End of variables declaration//GEN-END:variables

}
